# Generated by Django 3.1.6 on 2021-06-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('Month_Year_Start', models.CharField(max_length=50)),
                ('Month_Year_End', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school', models.CharField(max_length=100)),
                ('name_of_degree', models.CharField(max_length=100)),
                ('Month_Year_Start', models.CharField(max_length=50)),
                ('Month_Year_End', models.CharField(max_length=50)),
            ],
        ),
    ]
